imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

# Extra parameters
parameters:
    # List of available locales
    locales: [en]

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        #less:
        #    node:       /opt/local/bin/node
        #    node_paths: [/opt/local/lib/node, /opt/local/lib/node_modules]
        lessphp:
            file: %kernel.root_dir%/../vendor/lessphp/lessc.inc.php
            apply_to: "\.less$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Snowcap AdminBundle Configuration
#snowcap_admin:
#    bundle: YourAdminBundle
#    sections:
#        pages:
#            label: section_pages
#            admin_class: Your\AdminBundle\Admin\PageAdmin
#            entity_class: Snowcap\SiteBundle\Entity\Page
#            translation_entity_class: Snowcap\SiteBundle\Entity\PageTranslation

# Snowcap ImBundle Configuration
#snowcap_im:
#  formats:
#    thumbnail:
#        resize: 200x100^
#        gravity: center
#        crop: 200x100+0+0

# Zend Cache Configuration
#knp_zend_cache:
#    templates:
#        your_cache:
#            frontend:
#                name: Core
#                options:
#                    lifetime: 7200
#                    automatic_serialization: true
#            backend:
#                name: Apc
#                options:
#                    cache_dir: %kernel.root_dir%/cache/%kernel.environment%